window.FCContentData = window.FCContentData || {};
(() => {
  const VERSION = window.FCContentData.VERSION || "2026.1";
  window.FCContentData.VERSION = VERSION;

  const testBlueprints = [
{
      id: "test-c1-preliminaries",
      courseId: "calc-1",
      chapterId: "c1-preliminaries-basics",
      title: "Unit Test: Preliminaries",
      questionCount: 12,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["prelim.functions"], count: 2, difficulty: ["easy"] },
          { tags: ["prelim.graphs"], count: 2, difficulty: ["easy"] },
          { tags: ["prelim.polynomials"], count: 2, difficulty: ["easy"] },
          { tags: ["prelim.trig"], count: 2, difficulty: ["easy"] },
          { tags: ["prelim.exp_log"], count: 2, difficulty: ["easy"] },
          { tags: ["prelim.inverse"], count: 2, difficulty: ["easy"] },
        ],
      },
      rewards: { xp: 50, unlockSectionIds: ["c1-limits-intro"] },
      version: VERSION,
    },
{
      id: "test-c1-limits-basics",
      courseId: "calc-1",
      chapterId: "c1-limits-basics",
      title: "Unit Test: Limits and Continuity",
      questionCount: 12,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["limits.intro"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["limits.one_sided"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["limits.laws"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["limits.at_infinity"], count: 1, difficulty: ["medium"] },
          { tags: ["limits.infinite"], count: 1, difficulty: ["medium"] },
          { tags: ["limits.continuity"], count: 1, difficulty: ["easy", "medium"] },
          { tags: ["limits.discontinuities"], count: 1, difficulty: ["medium"] },
          { tags: ["limits.ivt"], count: 1, difficulty: ["medium"] },
          { tags: ["limits.trig"], count: 1, difficulty: ["easy"] },
          { tags: ["limits.squeeze"], count: 1, difficulty: ["easy", "medium"] },
        ],
      },
      rewards: { xp: 60, unlockSectionIds: ["c1-power-rule"] },
      version: VERSION,
    },
{
      id: "test-c1-deriv-basics",
      courseId: "calc-1",
      chapterId: "c1-deriv-basics",
      title: "Unit Test: Derivative Basics",
      questionCount: 10,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["derivatives.definition"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["derivatives.rate"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["derivatives.slope"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["derivatives.differentiability"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.higher_order"], count: 2, difficulty: ["medium"] },
        ],
      },
      rewards: { xp: 70, unlockSectionIds: ["c1-power-rule"] },
      version: VERSION,
    },
{
      id: "test-c1-deriv-rules",
      courseId: "calc-1",
      chapterId: "c1-deriv-rules",
      title: "Unit Test: Derivative Rules",
      questionCount: 12,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["derivatives.power_rule"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["derivatives.constant_multiple"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.sum_diff"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.product_rule"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.quotient_rule"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.chain_rule"], count: 2, difficulty: ["medium"] },
        ],
      },
      rewards: { xp: 80, unlockSectionIds: ["c1-deriv-poly"] },
      version: VERSION,
    },
{
      id: "test-c1-deriv-common",
      courseId: "calc-1",
      chapterId: "c1-deriv-common",
      title: "Unit Test: Derivatives of Common Functions",
      questionCount: 14,
      timeLimitSec: 1500,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["derivatives.polynomial"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.trig"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.inverse_trig"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.exponential"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.logarithmic"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.implicit"], count: 2, difficulty: ["medium"] },
          { tags: ["derivatives.log_diff"], count: 2, difficulty: ["hard"] },
        ],
      },
      rewards: { xp: 90, unlockSectionIds: ["c1-related-rates"] },
      version: VERSION,
    },
{
      id: "test-c1-derivatives-full",
      courseId: "calc-1",
      chapterId: "c1-deriv-apps",
      title: "Unit Test: Derivatives (Comprehensive)",
      questionCount: 32,
      timeLimitSec: 2400,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["derivatives.definition"], count: 1 },
          { tags: ["derivatives.rate"], count: 1 },
          { tags: ["derivatives.slope"], count: 1 },
          { tags: ["derivatives.differentiability"], count: 1 },
          { tags: ["derivatives.higher_order"], count: 1 },
          { tags: ["derivatives.power_rule"], count: 1 },
          { tags: ["derivatives.constant_multiple"], count: 1 },
          { tags: ["derivatives.sum_diff"], count: 1 },
          { tags: ["derivatives.product_rule"], count: 1 },
          { tags: ["derivatives.quotient_rule"], count: 1 },
          { tags: ["derivatives.chain_rule"], count: 1 },
          { tags: ["derivatives.polynomial"], count: 1 },
          { tags: ["derivatives.trig"], count: 1 },
          { tags: ["derivatives.inverse_trig"], count: 1 },
          { tags: ["derivatives.exponential"], count: 1 },
          { tags: ["derivatives.logarithmic"], count: 1 },
          { tags: ["derivatives.implicit"], count: 1 },
          { tags: ["derivatives.log_diff"], count: 1 },
          { tags: ["derivatives.related_rates"], count: 1 },
          { tags: ["derivatives.linear_approx"], count: 1 },
          { tags: ["derivatives.differentials"], count: 1 },
          { tags: ["derivatives.critical_points"], count: 1 },
          { tags: ["derivatives.monotonicity"], count: 1 },
          { tags: ["derivatives.concavity"], count: 1 },
          { tags: ["derivatives.inflection"], count: 1 },
          { tags: ["derivatives.first_derivative_test"], count: 1 },
          { tags: ["derivatives.second_derivative_test"], count: 1 },
          { tags: ["derivatives.curve_sketching"], count: 1 },
          { tags: ["derivatives.optimization"], count: 1 },
          { tags: ["derivatives.mvt"], count: 1 },
          { tags: ["derivatives.rolle"], count: 1 },
          { tags: ["derivatives.lhopital"], count: 1 },
        ],
      },
      rewards: { xp: 120, unlockSectionIds: ["c1-antiderivatives"] },
      version: VERSION,
    },
{
      id: "test-c1-int-integrals",
      courseId: "calc-1",
      chapterId: "c1-int-integrals",
      title: "Unit Test: Integrals (Introduction)",
      questionCount: 16,
      timeLimitSec: 1500,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["integrals.intro"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["integrals.antiderivatives"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["integrals.indefinite"], count: 2, difficulty: ["medium"] },
          { tags: ["integrals.basic_rules"], count: 2, difficulty: ["medium"] },
          { tags: ["integrals.riemann"], count: 2, difficulty: ["medium"] },
          { tags: ["integrals.definite"], count: 2, difficulty: ["easy", "medium"] },
          { tags: ["integrals.ftc"], count: 2, difficulty: ["medium"] },
          { tags: ["integrals.net_change"], count: 2, difficulty: ["medium"] },
        ],
      },
      rewards: { xp: 90, unlockSectionIds: [] },
      version: VERSION,
    },
{
      id: "test-c2-integrals-basics",
      courseId: "calc-2",
      chapterId: "c2-integrals-basics",
      title: "Unit Test: Techniques of Integration",
      questionCount: 12,
      timeLimitSec: 1500,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["integrals.substitution"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.by_parts"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.trig"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.trig_sub"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.partial_fractions"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.improper"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 110, unlockSectionIds: ["c2-area-between-curves"] },
      version: VERSION,
    },
{
      id: "test-c2-integral-apps",
      courseId: "calc-2",
      chapterId: "c2-integral-apps",
      title: "Unit Test: Applications of Integration",
      questionCount: 12,
      timeLimitSec: 1500,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["integrals.area_between_curves"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.volumes"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.arc_length"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.surface_area"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.work"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["integrals.average_value"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 110, unlockSectionIds: ["c2-parametric-curves"] },
      version: VERSION,
    },
{
      id: "test-c2-parametric-basics",
      courseId: "calc-2",
      chapterId: "c2-parametric-basics",
      title: "Unit Test: Parametric Equations",
      questionCount: 6,
      timeLimitSec: 900,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["parametric.curves"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["parametric.derivatives"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["parametric.arc_length"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 80, unlockSectionIds: ["c2-polar-graphs"] },
      version: VERSION,
    },
{
      id: "test-c2-polar-basics",
      courseId: "calc-2",
      chapterId: "c2-polar-basics",
      title: "Unit Test: Polar Coordinates",
      questionCount: 6,
      timeLimitSec: 900,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["polar.graphs"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["polar.area"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["polar.arc_length"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 80, unlockSectionIds: ["c2-seq-definition"] },
      version: VERSION,
    },
{
      id: "test-c2-sequences-basics",
      courseId: "calc-2",
      chapterId: "c2-sequences-basics",
      title: "Unit Test: Sequences",
      questionCount: 8,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["sequences.definition"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["sequences.limits"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["sequences.monotonic"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["sequences.bounded"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 90, unlockSectionIds: ["c2-series-intro"] },
      version: VERSION,
    },
{
      id: "test-c2-series-basics",
      courseId: "calc-2",
      chapterId: "c2-series-basics",
      title: "Unit Test: Series",
      questionCount: 10,
      timeLimitSec: 1200,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["series.intro"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.convergence"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.geometric"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.p_series"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.harmonic"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 100, unlockSectionIds: ["c2-test-comparison"] },
      version: VERSION,
    },
{
      id: "test-c2-convergence-tests",
      courseId: "calc-2",
      chapterId: "c2-convergence-tests",
      title: "Unit Test: Convergence Tests",
      questionCount: 12,
      timeLimitSec: 1500,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["series.comparison"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.limit_comparison"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.integral_test"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.alternating"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.ratio_test"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.root_test"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 110, unlockSectionIds: ["c2-power-series-rep"] },
      version: VERSION,
    },
{
      id: "test-c2-power-series",
      courseId: "calc-2",
      chapterId: "c2-power-series",
      title: "Unit Test: Power Series",
      questionCount: 14,
      timeLimitSec: 1800,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["series.power"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.radius"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.taylor"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.maclaurin"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.taylor_poly"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.error"], count: 2, difficulty: ["medium", "hard"] },
          { tags: ["series.manipulation"], count: 2, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 120, unlockSectionIds: [] },
      version: VERSION,
    },
{
      id: "test-c3-vectors-basics",
      courseId: "calc-3",
      chapterId: "c3-vectors-basics",
      title: "Unit Test: Vectors and Geometry",
      questionCount: 15,
      timeLimitSec: 1800,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["vectors.basics"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vectors.dot"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vectors.cross"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vectors.lines_planes"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vectors.quadric"], count: 3, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 120, unlockSectionIds: ["c3-vector-valued"] },
      version: VERSION,
    },
{
      id: "test-c3-vector-functions",
      courseId: "calc-3",
      chapterId: "c3-vector-functions-basics",
      title: "Unit Test: Vector Functions",
      questionCount: 18,
      timeLimitSec: 2100,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["vector_functions.definition"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_functions.limits"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_functions.derivatives"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_functions.integrals"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_functions.velocity"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_functions.arc_length"], count: 3, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 130, unlockSectionIds: ["c3-functions-multivariable"] },
      version: VERSION,
    },
{
      id: "test-c3-partials-basics",
      courseId: "calc-3",
      chapterId: "c3-partials-basics",
      title: "Unit Test: Functions of Several Variables",
      questionCount: 21,
      timeLimitSec: 2400,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["multivariable.functions"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["multivariable.limits"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["partials.basics"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["multivariable.higher_partials"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["multivariable.clairaut"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["multivariable.tangent_planes"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["multivariable.linear_approx"], count: 3, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 140, unlockSectionIds: ["c3-double-integrals"] },
      version: VERSION,
    },
{
      id: "test-c3-multiple-integrals",
      courseId: "calc-3",
      chapterId: "c3-multiple-integrals-basics",
      title: "Unit Test: Multiple Integrals",
      questionCount: 24,
      timeLimitSec: 2700,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["integrals.double"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.iterated"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.double_regions"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.double_polar"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.triple"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.cylindrical"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.spherical"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["integrals.jacobian"], count: 3, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 150, unlockSectionIds: ["c3-vector-fields"] },
      version: VERSION,
    },
{
      id: "test-c3-vector-calculus",
      courseId: "calc-3",
      chapterId: "c3-vector-calculus-basics",
      title: "Unit Test: Vector Calculus",
      questionCount: 30,
      timeLimitSec: 3300,
      passThreshold: 0.85,
      blueprint: {
        distribution: [
          { tags: ["vector_calc.fields"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.gradient"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.divergence"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.curl"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.line_integrals"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.conservative"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.greens"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.surface_integrals"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.stokes"], count: 3, difficulty: ["medium", "hard"] },
          { tags: ["vector_calc.divergence_theorem"], count: 3, difficulty: ["medium", "hard"] },
        ],
      },
      rewards: { xp: 160, unlockSectionIds: [] },
      version: VERSION,
    }
];

  window.FCContentData.testBlueprints = testBlueprints;
})();
